app.py
from flask import Flask, Blueprint, request
from views import views
#we import our views from the views file

app = Flask(__name__)
#we instantiate the app object

app.register_blueprint(views)
#we register the views Blueprint

if __name__ == "__main__":
    app.run(debug=True, port=8000)
#running the application


views.py
from flask import render_template, Blueprint, request

views = Blueprint("views", __name__)
task_list = []

@views.route("/")
def home():
    return render_template("index.html")

@views.route("/contact")
def contact():
    return render_template("contact.html")

@views.route("/about")
def about():
    return render_template("about.html")

@views.route("/todos", methods= ["GET", "POST"])
def todos():
    if request.method == "POST":
        task = request.form.get("task-input")
        task_list.append(task)
        print(task_list)
        return render_template("todos.html", task_list=task_list)
    return render_template("todos.html")

@views.route("/basket")
def basket():
    return render_template("basket.html")

@views.route("/seriesone")
def seriesone():
    return render_template("seriesone.html")

@views.route("/seriestwo")
def seriestwo():
    return render_template("seriestwo.html")

@views.route("/seriesthree")
def seriesthree():
    return render_template("seriesthree.html")

@views.route("/customercare")
def customercare():
    return render_template("customercare.html")   

@views.route("/checkout")
def checkout():
    return render_template("checkout.html")

@views.route("/product")
def item():
    return render_template("product.html")

templates/about.html
{% extends 'base.html' %}

{%block content %}
<div>
<h1>about: Obsidian City</h1>
</div>
<br>
<div>
    <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h2>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for("static", filename='css/styles.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200&display=swap" rel="stylesheet">
    <script src="{{url_for("static", filename="Js/main.js")}}" async></script>
    <title></title>
</head>
<body id-"base-body">
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for("views.home")}}"><h1>MONROVIA</h1></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for("views.about")}}">ABOUT</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for("views.contact")}}">CONTACT</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                SHOP
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{{url_for("views.seriesone")}}">Series One</a></li>
                <!-- <li><a class="dropdown-item" href="{{url_for("views.seriestwo")}}">Series Two</a></li>
                <li><a class="dropdown-item" href="{{url_for("views.seriesthree")}}">Series Three</a></li> -->
                <li><a class="dropdown-item" href="{{url_for("views.customercare")}}">Customer Care</a></li>
                <!-- <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                </ul>
            </li>
            <li class="nav-item">
                <!-- <a class="nav-link" href="{{url_for("views.basket")}}">SHOPPING BAG(0)</a> -->
            </li>

            <!-- create function that counts items in basket  -->
            <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
            </ul>
            <!-- <a class="nav-link" id="shop-counter" href="{{url_for("views.basket")}}">SHOPPING BAG + ${cartNumber}</a>  -->
            
            
            <!-- Wish to have a counter on the shopping bag icon that counts items in the cart -->
            
            <!-- <button class="btn btn-outline-success" type="submit">BUY</button> -->
            </form>
        </div>
        </div>
    </nav>
    
    {% block content %}
    {% endblock %}
<script src="{{url_for("static", filename="js/main.js")}}"></script>
</body>
</html>

templates/basket.html
{% extends 'base.html' %}

{%block content %}
<h1>basket</h1>
<br>
<td>
    <input class="uk-checkbox" type="checkbox"></td>
    <td><img class="uk-preserve-width uk-border-circle" src="static/images/cd_beetlebag.JPG "</td>
</td>
<!-- <h3> items:</h3>
<ol>
    <li>shout</li>
    <li>dm</li>
</ol>
<div>
    <ol>EMAIL</ol>
</div>
<div>
    <a>HAVE YOU SEEN:</a>
</div>
<br>
<div>
    <h2><a href= "{{url_for("views.checkout")}}">CHECKOUT:</a> </h2>
</div> -->
{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{%block content %}
<h1>CONTACT to Obsidian city</h1>
<br>
<h3> Top contact methods!</h3>
<div>
    <div>
    <a href="https://www.instagram.com/niggotiate__/">Dm me</a>
    </div>
    <br>
    <div>
    <a href="https://www.twitter.com/chalkedge/">Stalk me</a>
    </div>
    <br>
    <div>
    <form action="/action_page.php">
        <label for="contact">leave your email below</label>
    <br>
        <input type="text" id="contact" name="contact" value="">
        <button class="button"><a href="https://www.linkedin.com/in/peter-nwabuokei-aa4873154/">Let's catch up</a></button>
    </form>
    </div>
</div>
{% endblock %}

templates/customercare.html
{% extends 'base.html' %}

{% block content %}
<h1>CUSTOMER CARE</h1>
<br>
<h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet cursus sit amet dictum sit amet justo. Nisl rhoncus mattis rhoncus urna. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. <br> on blandit massa enim nec dui nunc mattis enim. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Libero nunc consequat interdum varius sit amet. Nulla facilisi etiam dignissim diam quis enim lobortis. In vitae turpis massa sed. Libero enim sed faucibus turpis in. Massa sapien faucibus et molestie ac feugiat sed. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Amet justo donec enim diam.</h2>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome to Obsidian city</h1>

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="static\images\cd_mistybag.JPG" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="static\images\cd_rubyredbag.JPG" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="static\images\cd_limon.JPG" class="d-block w-100" alt="...">
        </div>
    </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<br>
<div class="headline">
    <h2>Whats NEW.</h2>
</div>
<br>
<div class='container'>
    <div class='row'>
        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_beetlebag.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Beetlebag</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_campari.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Campari</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_limon.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Limon</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>


        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_mistybag.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Misty</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_orangebag.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">OrANGE</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_rubyredbag.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">RUBY JAY</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="uk-overflow-auto container" style = 'width: 70%'>
    <table class="uk-table uk-table-hover uk-table-middle uk-table-divider">
        <thead>
            <tr>
                <th class="uk-table-shrink"></th>
                <th class="uk-table-small sty"><h3>ITEM</h3></th>
                <th class="uk-table-small"></th>
                <th class="uk-width-small sty"><h3>PRICE</h3></th>
                <th class="uk-table-shrink uk-text-small sty"><h3>QUANTITY</h3></th>
                <th class="uk-table-shrink uk-text-small sty"><h3>TOTAL</h3></th>
            </tr>
        </thead>
        <tbody>
            <!-- <tr>
                <td><input class="uk-checkbox" type="checkbox"></td>
                <td><img class="uk-preserve-width uk-border-circle" src="${itemImage}" width="40" alt=""></td>
                <td class="uk-table-link">
                    <h3 class = "item-name">${item-name}</h3>
                </td>
                <td class="uk-text-truncate item-price"><h3>item price</h3></td>
                <td><input type = 'number' class = 'num' value = '1'></td>
                <td class="uk-text-truncate total-price"><h3>£</h3></td>
                <td><button class="uk-button uk-button-danger" type="button">Remove</button></td>
            </tr> -->

        </tbody>
        <tr>
            <td><input class="uk-checkbox" type="checkbox"></td>
            <td><img class="uk-preserve-width uk-border-circle"  width="40" alt=""></td>
            <td class="uk-table-link">
                <h3 class = "item-name"><strong>Grand-Total</strong></h3>
            </td>
            <td class="uk-text-truncate"><h3></h3></td>
            <td class="uk-text-truncate"><h3></h3></td>
            <td class="uk-text-truncate grand-total"><h3><strong></strong></h3></td>
        </tr>
    </table>
</div>
<br>
<br>
{% endblock %}

templates/seriesone.html
{% extends 'base.html' %}

{% block content %}
<h1>SERIES ONE</h1>


</div>
<br>
<div class='container'>
    <div class='row'>
        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_beetlebag.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Beetlebag</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_campari.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Campari</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_limon.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Limon</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>


        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_mistybag.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">Misty</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_orangebag.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">OrANGE</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

        <div class='col-md-4 col-lg-4'>
            <div class="card" style="width: 18rem;">
                <img src="static/images/cd_rubyredbag.JPG" class="card-img-top" alt="...">
                <div class="card-body">
                    <h3 class="card-title">RUBY JAY</h3>
                    <h4 class="card-text">£77</h4>
                    <a class="btn btn-outline-primary">Add to Cart</a>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="uk-overflow-auto container" style = 'width: 70%'>
    <table class="uk-table uk-table-hover uk-table-middle uk-table-divider">
        <thead>
            <tr>
                <th class="uk-table-shrink"></th>
                <th class="uk-table-small sty"><h3>ITEM</h3></th>
                <th class="uk-table-small"></th>
                <th class="uk-width-small sty"><h3>PRICE</h3></th>
                <th class="uk-table-shrink uk-text-small sty"><h3>QUANTITY</h3></th>
                <th class="uk-table-shrink uk-text-small sty"><h3>TOTAL</h3></th>
            </tr>
        </thead>
        <tbody>
            <!-- <tr>
                <td><input class="uk-checkbox" type="checkbox"></td>
                <td><img class="uk-preserve-width uk-border-circle" src="${itemImage}" width="40" alt=""></td>
                <td class="uk-table-link">
                    <h3 class = "item-name"></h3>
                </td>
                <td class="uk-text-truncate item-price"><h3>item price</h3></td>
                <td><input type = 'number' class = 'num' value = '1'></td>
                <td class="uk-text-truncate total-price"><h3>£</h3></td>
                <td><button class="uk-button uk-button-danger" type="button">Remove</button></td>
            </tr> -->

        </tbody>
        <tr>
            <td><input class="uk-checkbox" type="checkbox"></td>
            <td><img class="uk-preserve-width uk-border-circle"  width="40" alt=""></td>
            <td class="uk-table-link">
                <h3 class = "item-name"><strong>Grand-Total</strong></h3>
            </td>
            <td class="uk-text-truncate"><h3></h3></td>
            <td class="uk-text-truncate"><h3></h3></td>
            <td class="uk-text-truncate grand-total"><h3><strong></strong></h3></td>
        </tr>
    </table>
</div>
<br>
<br>
<br>

{% endblock %}